name: "Style check"
description: "Style check using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the variable
        PROJECT_PATH=$(pwd)

        echo $PROJECT_PATH

        # The command 'tr' translates, squeezes, and/or deletes characters from standard input, writing to standard output.
        # For example, in this case, we are replacing the character '\n' with a white-space (' ').
        # See: https://man7.org/linux/man-pages/man1/tr.1.html
        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/lib -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        # The command 'clang-format' is a tool to format C/C++/Java/JavaScript/Objective-C/Protobuf/C# code.
        # If no arguments are specified, it formats the code from standard input and writes the result to the standard output.
        # If <file>s are given, it reformats the files. If -i is specified together with <file>s, the files are edited in-place.
        # Otherwise, the result is written to the standard output.
        # For example, in this case, we are formating and editing the files inside '$SOURCE_FILES' in-place.
        # See: https://linuxcommandlibrary.com/man/clang-format
        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) > ${ERROR_FILE_FLAG}

        echo "Running: clang-format -i $SOURCE_FILES"

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Clang-format errors!!!
        path: $PROJECT_PATH/clang-format_errors.txt
        retention-days: 1
